name: Python docker login, build, push
run-name: ${{ github.actor }} Python 🚀
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker login  -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
          docker build . -t astinakerobokan/myserver:${GITHUB_RUN_NUMBER}
          docker push astinakerobokan/myserver:${GITHUB_RUN_NUMBER}
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: {%- raw -%} ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
