name: Python docker login, build, push
run-name: ${{ github.actor }} Python 🚀
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker login  -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
          docker build . -t astinakerobokan/myserver:${GITHUB_RUN_NUMBER}
          docker push astinakerobokan/myserver:${GITHUB_RUN_NUMBER}